import json
import os

notebook_path = '/home/franck/Documents/M2 OCC 2026/smart DATA-CITY/projet3/Cutisia_Master.ipynb'

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# The cell A3 is at index 7 (verified in previous view_file)
new_source = [
    "# === ÉTAPE A3 : Lancement du serveur FastAPI + Ngrok ===\n",
    "import io\n",
    "import os\n",
    "import cv2\n",
    "import json\n",
    "import time\n",
    "import uvicorn\n",
    "import nest_asyncio\n",
    "from PIL import Image\n",
    "from fastapi import FastAPI, UploadFile, File, Form\n",
    "from fastapi.middleware.cors import CORSMiddleware\n",
    "from pyngrok import ngrok\n",
    "\n",
    "# --- CONFIGURATION ---\n",
    "LABELS = ['Candidiase', 'Leprosy', 'Monkeypox', 'Mélanomes', 'Scabies', 'Tinea']\n",
    "IMG_SIZE = (384, 384)\n",
    "PORT = 8000\n",
    "NGROK_TOKEN = '3BlAngRylGIHjrS1492IQM3yT0C_7ocjnd4T6TrZzMLH2HmuE'\n",
    "COLLECT_DIR = \"/content/drive/MyDrive/new_cutisia_images\"\n",
    "\n",
    "# Création du dossier de collecte sur Drive\n",
    "if not os.path.exists(COLLECT_DIR):\n",
    "    try:\n",
    "        os.makedirs(COLLECT_DIR)\n",
    "        print(f'📁 Dossier de collecte créé : {COLLECT_DIR}')\n",
    "    except:\n",
    "        print('⚠️ Impossible de créer le dossier sur Drive, utilisation locale.')\n",
    "        COLLECT_DIR = 'new_cutisia_images'\n",
    "        if not os.path.exists(COLLECT_DIR): os.makedirs(COLLECT_DIR)\n",
    "\n",
    "# --- PRÉTRAITEMENT ---\n",
    "def equalize_derma(img):\n",
    "    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)\n",
    "    l, a, b = cv2.split(lab)\n",
    "    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))\n",
    "    l = clahe.apply(l)\n",
    "    lab = cv2.merge((l, a, b))\n",
    "    return cv2.cvtColor(lab, cv2.COLOR_LAB2RGB)\n",
    "\n",
    "def preprocess_image(image):\n",
    "    img = np.array(image.convert('RGB'))\n",
    "    img = cv2.resize(img, IMG_SIZE)\n",
    "    img = equalize_derma(img)\n",
    "    img = img.astype(np.float32) / 255.0\n",
    "    return np.expand_dims(img, axis=0)\n",
    "\n",
    "# --- API ---\n",
    "app = FastAPI(title='Cutisia Elite API')\n",
    "app.add_middleware(CORSMiddleware, allow_origins=['*'], allow_methods=['*'], allow_headers=['*'])\n",
    "\n",
    "@app.get('/')\n",
    "def home():\n",
    "    return {'status': 'online', 'model': 'EfficientNetV2-L', 'classes': LABELS}\n",
    "\n",
    "@app.post('/predict')\n",
    "async def predict(file: UploadFile = File(...)):\n",
    "    contents = await file.read()\n",
    "    image = Image.open(io.BytesIO(contents))\n",
    "    processed = preprocess_image(image)\n",
    "    predictions = model.predict(processed)\n",
    "    idx = int(np.argmax(predictions[0]))\n",
    "    return {\n",
    "        'class': LABELS[idx],\n",
    "        'confidence': float(predictions[0][idx]),\n",
    "        'results': {LABELS[i]: float(predictions[0][i]) for i in range(len(LABELS))}\n",
    "    }\n",
    "\n",
    "@app.post('/collect')\n",
    "async def collect(file: UploadFile = File(...), metadata: str = Form(...)):\n",
    "    \"\"\"Reçoit une image et un JSON, les enregistre sur le Drive\"\"\"\n",
    "    try:\n",
    "        timestamp = int(time.time() * 1000)\n",
    "        base_filename = f'collect_{timestamp}'\n",
    "        \n",
    "        # 1. Sauvegarde de l'image\n",
    "        ext = os.path.splitext(file.filename)[1] or '.jpg'\n",
    "        img_path = os.path.join(COLLECT_DIR, base_filename + ext)\n",
    "        with open(img_path, 'wb') as f:\n",
    "            f.write(await file.read())\n",
    "            \n",
    "        # 2. Sauvegarde des métadonnées JSON\n",
    "        json_path = os.path.join(COLLECT_DIR, base_filename + '.json')\n",
    "        with open(json_path, 'w', encoding='utf-8') as f:\n",
    "            f.write(metadata)\n",
    "            \n",
    "        return {'status': 'success', 'message': 'Données enregistrées', 'filename': base_filename}\n",
    "    except Exception as e:\n",
        "        return {'status': 'error', 'message': str(e)}\n",
    "\n",
    "# --- LANCEMENT ---\n",
    "ngrok.set_auth_token(NGROK_TOKEN)\n",
    "tunnel = ngrok.connect(PORT)\n",
    "public_url = tunnel.public_url\n",
    "\n",
    "print('\\n' + '='*60)\n",
    "print('🏥 CUTISIA ELITE AI - SERVEUR EN LIGNE')\n",
    "print('='*60)\n",
    "print(f'\\n🌍 URL PUBLIQUE : {public_url}')\n",
    "print(f'🔗 Endpoint API : {public_url}/predict')\n",
    "print(f'📂 Collecte vers : {COLLECT_DIR}')\n",
    "print(f'\\n📱 Copiez cette URL dans votre app Flutter :')\n",
    "print(f'   cloud_api_service.dart > baseUrl = \"{public_url}\"')\n",
    "print('\\n⚠️  Ne fermez PAS cette cellule tant que vous utilisez l\\'API!')\n",
    "print('='*60 + '\\n')\n",
    "\n",
    "nest_asyncio.apply()\n",
    "config = uvicorn.Config(app, host='0.0.0.0', port=PORT)\n",
    "server = uvicorn.Server(config)\n",
    "await server.serve()"
]

nb['cells'][7]['source'] = new_source

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2, ensure_ascii=False)

print("✅ Master Notebook updated successfully.")
